# Generated by Django 3.1.1 on 2020-09-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingJson', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
