# Generated by Django 3.1.1 on 2020-10-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingJson', '0002_auto_20201001_0136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='jsondatas',
            old_name='userId',
            new_name='userid',
        ),
    ]
