# Generated by Django 3.1.1 on 2020-10-01 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingJson', '0004_auto_20201001_1028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsondatas',
            old_name='userid',
            new_name='userId',
        ),
    ]
