# Generated by Django 3.1.1 on 2020-10-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingJson', '0005_auto_20201001_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondatas',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
